"""Build-time declaration migration directly to C#; no executable IR or runtime dependency.

Only literal Button/Template constructors and Page declarations/links are supported.
New control flow is an error requiring a native C# port, never interpreted here.
"""
import argparse
import ast
import hashlib
import json
from pathlib import Path

SERVERS = ("cn", "en", "jp", "tw")


def quoted(value):
    return "null" if value is None else json.dumps(value, ensure_ascii=False)


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def class_name(name):
    return "".join(part.title() for part in name.split("_"))


def expression(value, kind, length):
    if value is None or value == ():
        return "null"
    if not isinstance(value, tuple) or len(value) != length or any(type(v) is not int for v in value):
        raise ValueError(f"nonliteral {kind}: {value!r}")
    return f"new {kind}({', '.join(str(v) for v in value)})"


def variant_value(value, server):
    if isinstance(value, dict):
        if set(value) != set(SERVERS):
            raise ValueError("Incomplete or unknown server variant")
        return value[server]
    return value


def write(path, content, check):
    content = content.replace("\r\n", "\n")
    if check:
        if not path.is_file() or path.read_text(encoding="utf-8-sig").replace("\r\n", "\n") != content:
            raise ValueError(f"C# declaration drift: {path.name}")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")


def compile_rules(root, target, check):
    symbols = {}
    module_sources = {}
    all_assets = []
    expected_files = set()
    banner = "// <auto-generated>Direct upstream declarations; regenerate with tools/migration/compile_static_rules.py.</auto-generated>\n"
    for source in sorted((root / "module").rglob("assets.py")):
        relative = source.relative_to(root).as_posix()
        module = relative[:-3].replace("/", ".")
        group = class_name(source.parent.name)
        if module in symbols or group in module_sources:
            raise ValueError("Duplicate source module or generated class")
        module_sources[group] = source
        names = symbols[module] = {}
        lines = [banner, "namespace Alas.Engine.Rules;\n", "public static partial class UiAssets", "{", f"    public static class {group}", "    {",
                 f"        public static readonly SourceFile Source = new({quoted(relative)}, {quoted(digest(source))});"]
        for node in ast.parse(source.read_text(encoding="utf-8-sig")).body:
            if isinstance(node, (ast.Import, ast.ImportFrom)) or isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant):
                continue
            if not (isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name)
                    and isinstance(node.value, ast.Call) and isinstance(node.value.func, ast.Name)
                    and node.value.func.id in ("Button", "Template") and not node.value.args):
                raise ValueError(f"Unported declaration {relative}:{node.lineno}")
            name, call = node.targets[0].id, node.value
            if name in names:
                raise ValueError(f"Repeated asset declaration: {module}.{name}")
            values = {item.arg: ast.literal_eval(item.value) for item in call.keywords}
            allowed = {"file"} if call.func.id == "Template" else {"area", "button", "color", "file", "name"}
            if not set(values) <= allowed or None in values:
                raise ValueError(f"Unknown asset arguments: {module}.{name}")
            asset_id = f"{module}.{name}"
            reference = f"UiAssets.{group}.{name}"
            names[name] = reference
            all_assets.append(reference)
            # Generated assets use file basenames as upstream runtime names (including lowercase templates).
            raw_files = [variant_value(values.get("file"), server) for server in SERVERS]
            runtime_names = [values.get("name") or (Path(path).stem if path else "BUTTON") for path in raw_files]
            if call.func.id == "Template":
                runtime_names = [name.upper() for name in runtime_names]
            if len(set(runtime_names)) != 1:
                raise ValueError(f"Server-dependent asset names need explicit port: {asset_id}")
            lines.append(f"        public static readonly AssetRule {name} = new({quoted(asset_id)}, {quoted(runtime_names[0])}, AssetKind.{call.func.id}, Source, {node.lineno}, new(")
            for index, server in enumerate(SERVERS):
                area = expression(variant_value(values.get("area"), server), "Rectangle", 4)
                color = expression(variant_value(values.get("color"), server), "Rgb", 3)
                button = expression(variant_value(values.get("button"), server), "Rectangle", 4)
                file = raw_files[index]
                file_hash = None
                if file:
                    relative_file = Path(file)
                    if relative_file.is_absolute() or relative_file.parts[0] != "assets" or ".." in relative_file.parts:
                        raise ValueError("Asset declaration escapes assets root")
                    resolved = (root / file).resolve()
                    if not resolved.is_relative_to((root / "assets").resolve()):
                        raise ValueError("Asset path escapes resolved assets root")
                    file_hash = digest(resolved)
                tail = "));" if index == 3 else ","
                lines.append(f"            new({area}, {color}, {button}, {quoted(file)}, {quoted(file_hash)}){tail}")
        lines += ["    }", "}", ""]
        output = target / "Assets" / f"{group}.g.cs"
        expected_files.add(output)
        write(output, "\n".join(lines), check)
    index = target / "Assets" / "Catalog.g.cs"
    expected_files.add(index)
    write(index, banner + "using System.Collections.Immutable;\nnamespace Alas.Engine.Rules;\npublic static partial class UiAssets\n{\n"
          + "    private static partial ImmutableArray<AssetRule> CreateAll() =>\n    [\n"
          + "\n".join("        " + asset + "," for asset in all_assets) + "\n    ];\n}\n", check)
    extras = set((target / "Assets").glob("*.g.cs")) - expected_files
    if extras:
        raise ValueError("Stale generated C# declarations must be reviewed: " + ", ".join(sorted(path.name for path in extras)))

    source = root / "module/ui/page.py"
    page_symbols, pages = {}, []
    lines = [banner, "namespace Alas.Engine.Rules;", "public static class UpstreamPages", "{",
             f"    public static readonly SourceFile Source = new(\"module/ui/page.py\", {quoted(digest(source))});",
             "    public static PageGraph Create()", "    {", "        var graph = new PageGraphBuilder();"]
    for node in ast.parse(source.read_text(encoding="utf-8-sig")).body:
        if isinstance(node, ast.ImportFrom):
            if node.module not in symbols:
                raise ValueError(f"Unresolved page import: {node.module}")
            for alias in node.names:
                if alias.name == "*":
                    page_symbols.update(symbols[node.module])
                else:
                    page_symbols[alias.asname or alias.name] = symbols[node.module][alias.name]
        elif isinstance(node, (ast.Import, ast.ClassDef)) or isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant):
            continue
        elif (isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name)
              and isinstance(node.value, ast.Call) and isinstance(node.value.func, ast.Name) and node.value.func.id == "Page"
              and len(node.value.args) == 1 and not node.value.keywords):
            name = node.targets[0].id
            if name in pages:
                raise ValueError("Repeated Page needs explicit port")
            pages.append(name)
            argument = node.value.args[0]
            check_asset = "null" if isinstance(argument, ast.Constant) and argument.value is None else page_symbols[argument.id]
            lines.append(f"        var {name} = graph.Page({quoted(name)}, {check_asset});")
        elif (isinstance(node, ast.Expr) and isinstance(node.value, ast.Call) and isinstance(node.value.func, ast.Attribute)
              and node.value.func.attr == "link" and isinstance(node.value.func.value, ast.Name) and not node.value.args):
            call = node.value
            if {kw.arg for kw in call.keywords} != {"button", "destination"}:
                raise ValueError("Unknown Page.link arguments")
            values = {kw.arg: kw.value.id for kw in call.keywords}
            origin = call.func.value.id
            if origin not in pages or values["destination"] not in pages:
                raise ValueError("Unresolved page link")
            lines.append(f"        graph.Link({origin}, {page_symbols[values['button']]}, {values['destination']});")
        else:
            raise ValueError(f"Unported page declaration at line {node.lineno}")
    lines += ["        return graph.Build();", "    }", "}", ""]
    write(target / "UpstreamPages.g.cs", "\n".join(lines), check)
    print(f"Direct C# declarations {'verified' if check else 'written'}: {len(all_assets)} assets / {len(module_sources)} modules / {len(pages)} pages")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--upstream", required=True, type=Path)
    parser.add_argument("--output", type=Path, default=Path(__file__).resolve().parents[2] / "src/Alas.Engine/Rules/Generated")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    compile_rules(args.upstream, args.output, args.check)
