#!/usr/bin/env python3
"""Compile the upstream Campaign source inventory into a C# rule-source contract.

This compiler deliberately emits provenance and migration boundaries only.  It
does not emit an executable intermediate representation, method steps, or a
Python-compatible interpreter.  Campaign behavior must be ported as ordinary
C# methods before it is registered in ``RuleCatalog``.

The generated contract gives the Engine a complete, reviewable list of
upstream Campaign sources while keeping unsupported rules explicit.  A source
hash change or a stale generated file fails ``--check``; no missing source is
silently treated as a default rule.
"""
from __future__ import annotations

import argparse
import ast
import hashlib
import json
from pathlib import Path


BANNER = "// <auto-generated>Direct upstream Campaign source contract; regenerate with tools/migration/compile_campaign_rules.py.</auto-generated>"


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def quoted(value: object) -> str:
    return json.dumps(value, ensure_ascii=False)


def source_id(relative: str) -> str:
    return relative.removeprefix("campaign/").removesuffix(".py")


def _brief(node: ast.AST) -> str:
    try:
        text = ast.unparse(node)
    except Exception:  # pragma: no cover - defensive for future Python AST nodes
        text = type(node).__name__
    return " ".join(text.split())[:120]


def unsupported_methods(method: ast.FunctionDef | ast.AsyncFunctionDef) -> list[str]:
    """Return structural reasons that require a hand-written C# port.

    This is intentionally conservative.  It is a migration report, not a
    translator: any control-flow or dynamic construct outside the direct C#
    API must remain visible to a reviewer.
    """
    reasons: list[str] = []
    if isinstance(method, ast.AsyncFunctionDef):
        reasons.append(f"{method.name}@{method.lineno}: async source method")
    if method.decorator_list:
        reasons.append(f"{method.name}@{method.lineno}: decorator")
    for node in ast.walk(method):
        if isinstance(node, (ast.For, ast.AsyncFor, ast.While, ast.Try, ast.With,
                             ast.AsyncWith, ast.Match, ast.Yield, ast.YieldFrom,
                             ast.Lambda, ast.NamedExpr)):
            reasons.append(f"{method.name}@{node.lineno}: {type(node).__name__}")
        elif isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
            # A free function call has no typed CampaignContext equivalent by
            # default.  Calls through self are reviewed by the C# port itself.
            reasons.append(f"{method.name}@{node.lineno}: free call {_brief(node)}")
    return sorted(set(reasons))


def read_campaign(path: Path, relative: str) -> dict[str, object]:
    try:
        tree = ast.parse(path.read_text(encoding="utf-8-sig"), filename=relative)
    except SyntaxError as error:
        return {
            "id": source_id(relative), "source": relative, "sha256": digest(path),
            "has_campaign": False, "bases": [], "methods": [],
            "unsupported": [f"syntax error: {error}"],
        }

    campaign = next((node for node in tree.body
                     if isinstance(node, ast.ClassDef) and node.name == "Campaign"), None)
    if campaign is None:
        return {
            "id": source_id(relative), "source": relative, "sha256": digest(path),
            "has_campaign": False, "bases": [], "methods": [], "unsupported": [],
        }

    methods = [node for node in campaign.body if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))]
    unsupported = [reason for method in methods for reason in unsupported_methods(method)]
    return {
        "id": source_id(relative), "source": relative, "sha256": digest(path),
        "has_campaign": True,
        "bases": [ast.unparse(base) for base in campaign.bases],
        "methods": [method.name for method in methods],
        "unsupported": sorted(set(unsupported)),
    }


def collect(upstream: Path) -> list[dict[str, object]]:
    root = upstream / "campaign"
    if not root.is_dir():
        raise ValueError(f"missing upstream campaign directory: {root}")
    rows: list[dict[str, object]] = []
    for path in sorted(root.rglob("*.py")):
        if path.name == "__init__.py" or "__pycache__" in path.parts:
            continue
        relative = path.relative_to(upstream).as_posix()
        rows.append(read_campaign(path, relative))
    if not rows:
        raise ValueError("upstream campaign directory contains no Python sources")
    return rows


def render(rows: list[dict[str, object]]) -> str:
    lines = [BANNER, "using System.Collections.Frozen;", "using System.Collections.Immutable;", "",
             "namespace Alas.Engine.Rules;", "",
             "/// <summary>Complete upstream Campaign source inventory. Entries are provenance, not executable rules.</summary>",
             "public sealed record CampaignRuleSourceDescriptor(string Id, SourceFile Source, bool HasCampaign,",
             "    ImmutableArray<string> Bases, ImmutableArray<string> Methods, ImmutableArray<string> Unsupported);", "",
             "public static class CampaignRuleSourceCatalog", "{",
             "    public static readonly ImmutableArray<CampaignRuleSourceDescriptor> All = ["]
    for row in rows:
        bases = ", ".join(quoted(value) for value in row["bases"])
        methods = ", ".join(quoted(value) for value in row["methods"])
        unsupported = ", ".join(quoted(value) for value in row["unsupported"])
        lines.append(
            f'        new({quoted(row["id"])}, new({quoted(row["source"])}, {quoted(row["sha256"])}), '
            f'{str(row["has_campaign"]).lower()}, [{bases}], [{methods}], [{unsupported}]),')
    lines += [
        "    ];", "",
        "    private static readonly FrozenDictionary<string, CampaignRuleSourceDescriptor> Index =",
        "        All.ToFrozenDictionary(entry => entry.Id, StringComparer.Ordinal);", "",
        "    public static bool TryGet(string id, out CampaignRuleSourceDescriptor descriptor)",
        "        => Index.TryGetValue(id, out descriptor!);", "",
        "    public static CampaignRuleSourceDescriptor Get(string id) => TryGet(id, out var descriptor)",
        '        ? descriptor : throw new NotSupportedException($"Unknown upstream Campaign source: {id}");',
        "}", ""]
    return "\n".join(lines)


def write(output: Path, content: str, check: bool) -> None:
    content = content.replace("\r\n", "\n")
    if check:
        if not output.is_file() or output.read_text(encoding="utf-8-sig").replace("\r\n", "\n") != content:
            raise ValueError(f"C# Campaign source contract drift: {output}")
        return
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--upstream", required=True, type=Path)
    parser.add_argument("--output", type=Path,
                        default=Path(__file__).resolve().parents[2] /
                        "src/Alas.Engine/Rules/Generated/CampaignRuleSources.g.cs")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rows = collect(args.upstream)
    write(args.output, render(rows), args.check)
    campaigns = sum(bool(row["has_campaign"]) for row in rows)
    unsupported = sum(bool(row["unsupported"]) for row in rows if row["has_campaign"])
    print(f"Campaign source contract {'verified' if args.check else 'written'}: "
          f"{len(rows)} sources / {campaigns} Campaign classes / {unsupported} requiring direct C# review")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
